version: '6.0.1'
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
  postgres:
    image: postgres:latest
    ports:
      - 5001:5001
    env_file:
      - .postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
