version: '6.0.1'
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .mongodb.env
