version: '3.1'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5001:5432
    env_file:
      - .postgres.local.env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
